inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.4
  Exclude:
    - Rakefile
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 25

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: implicit

RSpec/AnyInstance:
  Enabled: false
